// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQGZ3l474s5R5SvsbZSZSFPeEwjXLvxQ',
    appId: '1:1020447797202:android:05656b7def3f957b5ee20b',
    messagingSenderId: '1020447797202',
    projectId: 'first-vapas',
    storageBucket: 'first-vapas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL-BhqAJMVNH_mcuHbfEVOhbOx8qv4u_s',
    appId: '1:1020447797202:ios:fc7009941197c8445ee20b',
    messagingSenderId: '1020447797202',
    projectId: 'first-vapas',
    storageBucket: 'first-vapas.appspot.com',
    androidClientId: '1020447797202-ut6tui9rm7th0gcm2m0i43a5obedcil9.apps.googleusercontent.com',
    iosClientId: '1020447797202-4i9ubr4mpikk9r0rnigufo88s5a8kltn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMessenger',
  );
}
